services:
  bdd :
    image : mysql
    environment :
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mcdo
    ports :
      - 3306:3306
  pda : 
    image : phpmyadmin
    environment:
      - PMA_HOST=bdd
    ports :
      - 8080:80